# Generated by Django 4.1.5 on 2023-01-05 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 5, 11, 37, 5, 177179)),
        ),
    ]
