# Generated by Django 4.1.5 on 2023-01-06 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_publicda_alter_receita_date_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='publicda',
            new_name='publicado',
        ),
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 6, 8, 4, 55, 471291)),
        ),
    ]
